### ISSUE TITLE
Write test cases for the Activity API Endpoint

### ISSUE THREAD

**Issue by stobbei** [anjaneyak10/smarter-university-system#37]
Write API test cases for the /activity API POST endpoint, covering expected and unexpected results.  The parameters are:

  - text
  -  directed
  - recipients

And testing the valid users:
● cdarwin
● tedison
● einstein

**Comment by SambaSiveshKurra** [comment]
Activity for #5

**Comment by anjaneyak10** [comment]
Looks good
