### ISSUE TITLE
Write 2 unit tests for the quizzes module

### ISSUE THREAD

**Issue by stobbei** [anjaneyak10/smarter-university-system#38]
Write and run 2 new unit tests for the quizzes module by writing two new functions in the `quizzes_test.py` file.  For ease of use across the team call the functions `test_expose_failure_02` and `test_expose_failure_03`

**Comment by HarshVanasiwala-18** [comment]
Activity #6

**Comment by stobbei** [comment]
Unit tests look great. Excellent job finding the program bugs!

**Comment by HarshVanasiwala-18** [comment]
Done with the unit test and closing the Issue
