### ISSUE TITLE
Write 1 unit test for the quizzes module

### ISSUE THREAD

**Issue by qifu7** [anjaneyak10/smarter-university-system#52]
Write and run 1 new unit tests for the quizzes module by writing two new functions in the quizzes_test.py file. For ease of use across the team call the functions test_expose_failure_01.

**Comment by qifu7** [comment]
Activity https://github.com/anjaneyak10/smarter-university-system/issues/6

**Comment by anjaneyak10** [comment]
LGTM.

**Comment by HarshVanasiwala-18** [comment]
Looks Good
